#!/bin/bash

#set -x 

PACKAGE_PATH="$1"
CURR_PATH="$(pwd)"
TRASH_PATH="/home/$(whoami)/TRASH/"

# check path file/dir
if [ -z $PACKAGE_PATH ]; then
    echo "Warning - path is empty!"
    exit 1
fi

# create TRASH folder if is not exist
if [ ! -d $TRASH_PATH ]; then
    mkdir $TRASH_PATH
fi

# delete file older than 2 days
find $TRASH_PATH -type f -mtime +2 -delete

# If $FILE_PATH current folder - replace to absolute path
if echo $PACKAGE_PATH | grep -q '^\.\/'; then
    PACKAGE_PATH="$CURR_PATH/$(echo $PACKAGE_PATH | sed 's/\.\///')"
elif ! echo $PACKAGE_PATH | grep -q '^\/'; then
    PACKAGE_PATH="$CURR_PATH/$PACKAGE_PATH"
fi

# check symlink
if [ -L $PACKAGE_PATH ]; then
    if [ -e $PACKAGE_PATH ]; then
         echo "Delete sumlink to file $(readlink $PACKAGE_PATH)"
         unlink $PACKAGE_PATH
         exit 0
    else
        echo "Warning broken link to file $(readlink $PACKAGE_PATH)"
        exit 1
    fi
elif [ -f $PACKAGE_PATH ]; then

    # check hardlink
    INODE=$(stat $PACKAGE_PATH | awk '/'Inode'/ {print $4}')
    if [ ! -z $INODE ]; then
        COUNT_INODE_FILES=$(find $CURR_PATH -inum $INODE | wc -l)
        if [ $COUNT_INODE_FILES -gt 1 ]; then

            echo "Sucess delete hardlink ${PACKAGE_PATH}"
            #echo $COUNT_INODE_FILES
            rm -f $PACKAGE_PATH
            echo $(find $CURR_PATH -inum $INODE)
            exit 0

        else
            # package & move file
            lzma $PACKAGE_PATH && mv "$PACKAGE_PATH.lzma" $TRASH_PATH &>/dev/null
            if [ $? -eq 0 ]; then
                echo "Success delete \"$PACKAGE_PATH\""
                exit 0
            else
                echo "Fail delete \"$PACKAGE_PATH\""
                exit 1
            fi
        fi
    fi

elif [ -d $PACKAGE_PATH ]; then
    # package & move dir
    tar --ignore-failed-read -zcf "$PACKAGE_PATH.tar.gz" $PACKAGE_PATH && mv "$PACKAGE_PATH.tar.gz" $TRASH_PATH && rm -rf $PACKAGE_PATH &>/dev/null
    if [ $? -eq 0 ]; then
        echo "Success delete \"$PACKAGE_PATH\""
        exit 0
    else
        echo "Fail delete \"$PACKAGE_PATH\""
        exit 1
    fi
else
    echo "Warning - file or dir path \"$PACKAGE_PATH\" is empty!"
    exit 1
fi





